### ISSUE TITLE
Breaking change

### ISSUE THREAD

**Issue by victorolinasc** [primait/posexional#16]
Hi people! 

Recent updates broke the default behaviour of the library. [This line](https://github.com/primait/posexional/blob/master/lib/posexional/file.ex#L62) changed the "trim" behaviour.

That is not an issue to us, but I guess it should be mentioned in a changelog or something.

The difference is that now it trims everything and not only removes white spaces. We had some validations on size and performed trimming on our side so that is ok for us, but it was a bit misleading the change.

**Comment by chess4ever** [comment]
Hi @victorolinasc! Thanks for opening the issue. Actually this was an oversight. I think we will just go back to the previous behaviour.

**Comment by neslinesli93** [comment]
Hi @victorolinasc 

We've tried to repro this, but we can't manage to find a test case that breaks our implementation. Could you please provide an example of the broken behaviour? Thanks

**Comment by victorolinasc** [comment]
This simple test reproduces it:

```elixir
    test "posexional breaking change" do
      defmodule MyFile do
        use PosexionalFile

        row :some, &__MODULE__.row?/1 do
          value(:any_value, 3, filler: ?0, alignment: :right)
        end

        def row?("00" <> _), do: true
      end

      assert Posexional.File.read(MyFile.get_file(), "001") == [some: [any_value: "001"]]
    end
```

It will fail currently and would not fail before. The result now is: `[some: [any_value: "1"]]` which is my understanding that it shouldn't be like that (single char).

**Comment by chess4ever** [comment]
Hi Victor, you are right that the behaviour of the read/2 function has changed and we will update the changelog accordingly. 
It was modified by the PR https://github.com/primait/posexional/pull/6 which made the code reflect the behaviour as described in the Hex docs.
