### ISSUE TITLE
Elixir 1.5

### ISSUE THREAD

**Issue by squaini** [primait/posexional#2]
warning: variable "deps" does not exist and is being expanded to "deps()", please use parentheses to remove the ambiguity or change the variable name
mix.exs:11

warning: variable "description" does not exist and is being expanded to "description()", please use parentheses to remove the ambiguity or change the variable name
mix.exs:12

warning: variable "package" does not exist and is being expanded to "package()", please use parentheses to remove the ambiguity or change the variable name
mix.exs:13

==> posexional
Compiling 11 files (.ex)
warning: String.ljust/3 is deprecated, use String.pad_trailing/3 with a binary padding
  lib/posexional/field.ex:35

warning: String.rjust/3 is deprecated, use String.pad_leading/3 with a binary padding
  lib/posexional/field.ex:40

warning: String.to_char_list/1 is deprecated, use String.to_charlist/1
  lib/posexional/field.ex:66

**Comment by matteosister** [comment]
fatto! pubblicata nuova versione...
