### ISSUE TITLE
Parsing file with different rows' structure

### ISSUE THREAD

**Issue by GPrimola** [primait/posexional#28]
Hey guys,

I'm trying to use this lib to parse a positional file with different rows' structure.

For instance:

```
000B1    1AA01george----  !
001B102251943Liverpool
002B1voice
002B1guitar
002B1sitar
000B2    2AA01john------  !
001B210091940Liverpool
002B2voice
002B2electricguitar
002B2piano
002B2harmonica
```

Can this be defined with a multi row `PosexionalFile`?

**Comment by chess4ever** [comment]
Hi @GPrimola! It really depends on the structure of your rows. Are you able to extract patterns such that each pattern has always the same structure (considered as a positional row)?
For example I can see that line starting with `002B2` are followed by an instrument. Given that the length of the instrument is 14 characters, you could define a row like this for example:
```elixir
defmodule Row do
    use PosexionalRow

    guesser &__MODULE__.guesser/1

    @spec guesser(binary) :: boolean
    def guesser("002B2" <> _), do: true

    def guesser(_), do: false

    name :two_b_two

    fixed_value "002B2"
    value :instrument, 14
  end
```

**Comment by GPrimola** [comment]
Hey @chess4ever,

Thank you for your reply!

> Are you able to extract patterns such that each pattern has always the same structure (considered as a positional row)?

Yes, the posix file I'm dealing with has a structure, we have a parent line that's followed by a sequence of other lines that has different pattern than the parent one. Also there are metadata rows too. So despite it is a posix file, it has some structure inside, that's why I need to customize the pattern of each line.
I think your proposal helps to solve the issue, I just don't know how to use this on the `PosexionalFile` file.

Can I do something like?

```elixir
defmodule MyFile do
  use PosexionalFile

  row MyRow1
  row MyRow2
  ...
end
```

**Comment by chess4ever** [comment]
Exactly! If the `guesser` functions are exclusive you are just fine! Otherwise the first row that matches will be used for parsing and so you will be relying on the order of your `row` definitions.
