### ISSUE TITLE
Wrong typespecs

### ISSUE THREAD

**Issue by victorolinasc** [primait/posexional#9]
Hi! Thanks for your nice library.

I have an issue with dialyzer with the read functions. They may return `[binary()]` other than `Keyword.t()`.

I have to add an exception to dialyzer because of this.

**Comment by chess4ever** [comment]
Actually I think it should be `[tuple() | String.t()]`.

**Comment by chess4ever** [comment]
Fixed by commit https://github.com/primait/posexional/commit/8113fb2fd2b15a875ae96c4b83d86258af95899f
in version 0.5.0

**Comment by victorolinasc** [comment]
@chess4ever can you release version 0.5.0?

**Comment by chess4ever** [comment]
> @chess4ever can you release version 0.5.0?

@victorolinasc Done!
